version: "3.8"

services:
  app:
    image: cybulde-data
    container_name: cybulde-data
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-kyuksel}"
        USER_ID: "${UID:-1000}"
    env_file:
      - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME}/.ssh
    ipc: host
    init: true
    user: "${UID:-1000}"
    hostname: emkademy
