defaults:
  - dataset_reader_manager_schema
  - dataset_reader@dataset_readers.ghc: ghc_dataset_reader
  - dataset_reader@dataset_readers.jigsaw_toxic_comments: jtc_dataset_reader
  - dataset_reader@dataset_readers.twitter: twitter_dataset_reader
